#pragma once

#include "Demo.h"

#define MATERIAL_MOON_NAME "MoonMat"
#define TEXTURE_MOON_NAME "MoonTex"

#define MATERIAL_ROCKSIDE_NAME "RockSideMat"
#define TEXTURE_ROCKSIDE_NAME "RockSideTex"

#define MATERIAL_DEBUGCUBE_NAME "DebugCubeMat"
#define TEXTURE_DEBUGCUBE_NAME "DebugCubeTex"

#define MATERIAL_CUTTERALLY_NAME "CUTTERALLYMat"
#define TEXTURE_CUTTERALLY_NAME "CUTTERALLYTex"

#define MATERIAL_KAMRADALLY_NAME "KAMRADALLYMat"
#define TEXTURE_KAMRADALLY_NAME "KAMRADALLYTex"

#define MATERIAL_MINIONSALLY_NAME "MINIONSALLYMat"
#define TEXTURE_MINIONSALLY_NAME "MINIONSALLYTex"

#define MATERIAL_CUTTERENEMY_NAME "CUTTERENEMYMat"
#define TEXTURE_CUTTERENEMY_NAME "CUTTERENEMYTex"

#define MATERIAL_KAMRADENEMY_NAME "KAMRADENEMYMat"
#define TEXTURE_KAMRADENEMY_NAME "KAMRADENEMYTex"

#define MATERIAL_MINIONSENEMY_NAME "MINIONSENEMYMat"
#define TEXTURE_MINIONSENEMY_NAME "MINIONSENEMYTex"

#define MATERIAL_CARDBARACK_NAME "CARDBARACKMat"
#define TEXTURE_CARDBARACK_NAME "CARDBARACKTex"

#define MATERIAL_CARDCUTTER_NAME "CARDCUTTERMat"
#define TEXTURE_CARDCUTTER_NAME "CARDCUTTERTex"

#define MATERIAL_CARDHEALING_NAME "CARDHEALINGMat"
#define TEXTURE_CARDHEALING_NAME "CARDHEALINGTex"

#define MATERIAL_CARDKAMRAD_NAME "CARDKAMRADMat"
#define TEXTURE_CARDKAMRAD_NAME "CARDKAMRADTex"

#define MATERIAL_CARDMINIONS_NAME "CARDMINIONSMat"
#define TEXTURE_CARDMINIONS_NAME "CARDMINIONSTex"

#define MATERIAL_BARACKBUILD_NAME "BARACKBUILDMat"
#define TEXTURE_BARACKBUILD_NAME "BARACKBUILDTex"

#define MATERIAL_BARACKHEALBUILD_NAME "BARACKHEALBUILDMat"
#define TEXTURE_BARACKHEALBUILD_NAME "BARACKHEALBUILDTex"

#define MATERIAL_CARDBODYBUILDER_NAME "CARDBODYBUILDERMat"
#define TEXTURE_CARDBODYBUILDER_NAME "CARDBODYBUILDERTex"

#define MATERIAL_CARDSOLDIER_NAME "CARDSOLDIERMat"
#define TEXTURE_CARDSOLDIER_NAME "CARDSOLDIERTex"

#define MATERIAL_BODYBUILDERALLY_NAME "BODYBUILDERALLYMat"
#define TEXTURE_BODYBUILDERALLY_NAME "BODYBUILDERALLYTex"

#define MATERIAL_BODYBUILDERENEMY_NAME "BODYBUILDERENEMYMat"
#define TEXTURE_BODYBUILDERENEMY_NAME "BODYBUILDERENEMYTex"

#define MATERIAL_SOLDIERSALLY_NAME "SOLDIERALLYMat"
#define TEXTURE_SOLDIERALLY_NAME "SOLDIERALLYTex"

#define MATERIAL_SOLDIERENEMY_NAME "SOLDIERENEMYMat"
#define TEXTURE_SOLDIERENEMY_NAME "SOLDIERENEMYTex"